# -*- coding: utf-8 -*-
"""Ranking system_Delhi(IR Project)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1reFsGx9wHERjh23vC5y-LH0YJlkkfRkT
"""

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
import ast

nltk.download('vader_lexicon')
skywalker = SentimentIntensityAnalyzer()

df=pd.read_csv("/content/drive/MyDrive/IR_Project/delhi_hotels_details_final_freq.csv")
x=df["reviews"].to_dict()
score=[]
for i in x:
  res = ast.literal_eval(x[i])
  jedi=pd.DataFrame.from_dict(res, orient='columns')
  jedi["Review_Heading"]=jedi["Review_Heading"].str.replace('”','')
  jedi["Review"] = jedi[['Review_Heading', 'Review_Body']].agg(' '.join, axis=1)
  jedi['sentiment'] = jedi['Review'].apply(lambda x: skywalker.polarity_scores(x)['compound'])
  jedi = jedi.astype({'Review_Rating':'float'})
  result = jedi['Review_Rating'].multiply(jedi['sentiment'], axis="index")
  f=result.mean()
  score.append(f)
df['Score'] = score

df=df.drop(['Unnamed: 0.1'], axis=1)
df=df.drop(['Unnamed: 0'], axis=1)
df=df.drop(['overall_rating'], axis=1)
column_to_move = df.pop("Score")
df.insert(4, "Score", column_to_move)

Sith =df.sort_values('Score', ascending=False) #ranking of hotels according to score
Sith.head()

score=[]
for ind in df.index:
  x=df['Score'][ind]
  if '110006' in df['Location'][ind]:
    x=x*2
  if '110001' in df['Location'][ind]:
    x=x*1.9
  if '110075' in df['Location'][ind]:
    x=x*1.8
  if '110003' in df['Location'][ind]:
    x=x*1.7
  if '110032' in df['Location'][ind]:
    x=x*1.6
  if '110016' in df['Location'][ind]:
    x=x*1.5
  if '110021' in df['Location'][ind]:
    x=x*1.4
  if '110030' in df['Location'][ind]:
    x=x*1.3
  if '110065' in df['Location'][ind]:
    x=x*1.2
  if '110085' in df['Location'][ind]:
    x=x*1.1
  score.append(x)
df['TouristScore'] = score  
column_to_move = df.pop("TouristScore")
df.insert(4, "TouristScore", column_to_move)

Sith =df.sort_values('TouristScore', ascending=False) #ranking of hotels according to score
Sith.head()

Sith.shape

from google.colab import files
Sith.to_csv('TouristRankedHotelsDelhi.csv', sep='\t', index=False,header=True)
files.download('TouristRankedHotelsDelhi.csv')